# Generated by Django 4.0.6 on 2022-07-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField(default=5000)),
                ('band', models.CharField(default='4g', max_length=100)),
                ('display', models.CharField(max_length=150)),
                ('processor', models.CharField(max_length=120)),
            ],
        ),
    ]
