# Generated by Django 4.0.6 on 2022-08-09 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0005_alter_reviews_rating_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('incart', 'incart'), ('order_placed', 'order_placed'), ('cancelled', 'cancelled')], default='incart', max_length=100),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
